package com.example.demo.controller;

import com.example.demo.DBConnect;
import org.dom4j.rule.Mode;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import com.example.demo.model.*;
import org.springframework.web.servlet.ModelAndView;

@Controller // This means that this class is a Controller
@RequestMapping(path="/register") // This means URL's start with /demo (after Application path)
public class RegistrationController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;
    @Autowired
    private DBConnect conn;

    @GetMapping(path="/register")
    public ModelAndView GetRegister() {
        ModelAndView mav = new ModelAndView();
        mav.setViewName("register");
        return mav;
    }

    // GOD DAMN I WANNA DIE AFTER WRITING THIS :(
    // IM SORRY
    @PostMapping(path="/register") // Map ONLY POST Requests
    public void addNewUser (@RequestParam("Firstname") String firstname, @RequestParam("Surname") String surname,
                                                  @RequestParam("Id_Number") String idnum, @RequestParam("Race") String race,
                                                  @RequestParam("Gender") String gender,@RequestParam("Province") String province)
    {
        conn.excuteQuery("INSERT INTO User (`Firstname`, `Surname`, `Id_Number`, `Gender`, `Race`, `Province`)" +
                "VALUES ('" + firstname +"','" + surname+"','" + idnum+"','"+ gender+"','"+ race+"','" +province+"')");
        return ;
    }
}